ansible_connection: network_cli
ansible_user: cisco
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_password: cisco
ansible_network_os: asa
ansible_ssh_common_arg: -o KexAlgorithms=+diffie-hellman-group1-sha1
